### PR TITLE
Add @non_exposed decorator

### PR DESCRIPTION
**Pull request by brmzkw**
The @non_exposed decorator is used to wrap a method of a subclass of FlaskView to avoid exposing it as a view.

### CODE REVIEW

**Comment by brmzkw** [comment]
Tests still fail using Python3, but the problem doesn't appear to come from my changes but from dcf62b46f0

**Comment by apiguy** [comment]
@brmzkw Thank you for this! Before I merge it in I'd like to hear about your use case. Presently, Flask-Classy supports this behavior by prefixing a method name with an underscore. What case did you find where that didn't work for you?

**Comment by brmzkw** [comment]
@apiguy I don't like being defensive when I choose a method name. It means that unless there's a very special reason why it should be private (eg. an internal helper that isn't supposed to be used by subclasses), all methods are public.

All my classy views inherit a BaseView that declares non view methods. Currently, those views must begin with an underscore which breaks my coding style.

**Comment by apiguy** [comment]
Interesting, and understandable. Typically in python when you want to indicate a method is "private" you include a prefixed underscore (or double underscore if you want python to do some obfuscation on your behalf).

If I understand what you're saying, it's that you have methods that you wouldn't consider "private" but that you still don't want to expose. Is that right?

This is something I've considered myself a few times and I think it's a pretty good point.

**Comment by brmzkw** [comment]
Yep, you got the point :)

**Comment by bchatelard** [comment]
:+1:

**Pull request merged**
