### PR TITLE
Rework trailing slash urls

### PR DESCRIPTION
**Pull request by kpanic**
When using:

`trailing_slash = True` -- the default

I had mixed URLs for:
- POST (trailing slash)
- GET (trailing slash)
- GET id (no trailing slash)
- PUT id (no trailing slash)
- DELETE id (no trailing slash)

I don't know if this behaviour was intended.
Anyway I have prepared this PR to adapt the behaviour, I will close it if it does not make sense

Other **note**. With this patch if someone uses `trailing_slash = True` it will get consistent trailing slashes and `301` redirects to trailing slash urls

Other than the change itself, I adapted the pre-existing tests that were failing after introducing 804f20b

Let me know thanks ;)

### CODE REVIEW

**Comment by kpanic** [comment]
hey @apiguy does still makes sense this PR? (2 months old github says) thanks ;)

**Comment by apiguy** [comment]
Hi @kpanic - sorry for the delay I've been traveling more than usual these past couple months and haven't been able to keep up with some reported issues.

The thinking is that resources specifically identified (including an ID) should not have a trailing slash, but those URIs which are dealing with a type of resource in general would have a trailing slash. I believe we ended up with this approach to maintain compatibility with some 3rd party REST client tools that had this expectation.

**Comment by kpanic** [comment]
Hey @apiguy no worries :) btw, thanks for the reply eheh!
1) Do you remember what 3rd party REST client tools would expect that behaviour?
2) And would it make sense to add some config variable to activate this coherent behaviour while maintaining the current one by default?

If you will not consider 2) worth it I will close this PR

Thanks! :)

**Comment by kpanic** [comment]
I will close this Pull Request, it's too old ;) (Still mergeable!) eheh

**Pull request closed without merging**
