### PR TITLE
Add decorated view test

### PR DESCRIPTION
**Pull request by shuhaowu**
As you can see, a failure is expected. Not sure why yet. Will be trying
to fix in the next little while.

Address #23

### CODE REVIEW

**Comment by shuhaowu** [comment]
It looks like the issue originate on line 226. When wrapping is usually done, there is only `args` and `kwargs` left.

This looks like it is the problem of `wraps` rather than anything else. See http://stackoverflow.com/questions/3972290/how-can-i-get-the-argument-spec-on-a-decorated-function

I'm not sure how to workaround this. I suggest that we expand the current `decorators` to accept a dictionary mapping.

**Comment by apiguy** [comment]
interesting. originally I wasn't using `wraps` but the change was made a couple months ago to use it. https://github.com/apiguy/flask-classy/commit/6ec809a4184acb8a5a2c343a01515a0630b15c5e

I wonder if reverting that would give us back our sane argspec.

**Comment by apiguy** [comment]
I'm currently in an airport and can't check this all out completely - but I'll likely be working on this tomorrow.

**Comment by apiguy** [comment]
I see the issue... it looks like anything that uses `functools.wraps` to create a decorator throws away the ArgSpec and internalizes everything into a partial function application. It's annoying that it does that.

I think the fastest route to moving on would be to write your own login_required decorator, it's only about 5 lines of code. So long as you don't use the `functools.wraps` method it should work fine.

**Comment by shuhaowu** [comment]
Without `wraps` we lose the name of the function.

**Pull request merged**
